### ISSUE TITLE
Le futur de la validation côté serveur avec JSON schema

### ISSUE THREAD

**Issue by chandelieraxel** [StrasbourgJS/talks#11]
### Contenu

Brève présentation des besoins d'une validation des données côté serveur, example d'une validation manuelle pour démontré la complexité et le besoin d'avoir recours à des librairies tel que Joi (avec une comparaison des exemples situé avant)
Tout cela pour présenter JSON schema, qui est une nouvelle spécification pour la validation des données.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [x] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Chandelier Axel
- Twitter : @ChandelierAxel
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Salut @chandelieraxel,

Ton sujet serait-il encore prêt à être partagé avec la communauté ?
Si oui, on peut le prévoir pour le prochain meet-up!

**Comment by mfrachet** [comment]
Je me permet de cloturer cette issue puisqu'elle n'a pas recu d'activite depuis un moment :) . Hesitez pas a reouvrir si le sujet redevient d'actualite !

Merci 🙏🏻
