### ISSUE TITLE
Introduction à SolidJS

### ISSUE THREAD

**Issue by Julienng** [StrasbourgJS/talks#12]
# Introduction à solid js

## À propos du talk

Une introduction à solid-js et à sa réactivité (fine-grained reactivity). Les avantages et différences par rapport à React.

### Contenu

Le but est de faire une introduction qui explique d'abord ce qu'est solid-js, sa reactivité et le gain apporté.
Le concept général des signaux, qu'est-ce que ça comporte pour solid-js (createSignal, createEffect, state dérivé, memo)
Puis, de montrer à quoi ressemble le code et de mettre en avant les différences face à React.

Notamment : 
- Setup Component vs render Component
- Reactivité est un concept général, contrairement au state de react qui est associé à l'instance d'un composant.
- Le control flow : condition, boucle.

En conclusion, la reactivité dans les frameworks revient sur le devant de la scène avec des débats et implémentation runtime (vue, angular, preact, qwik) et de la réactivité via compilation (svelte, et react dans une certaine mesure avec le projet "forget" en cours d'expérimentation). C'est donc le bon moment pour s'informer sur les avantages & désavantages de celle-ci.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [x] 10 minutes
- [ ] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Cavaleiro Julien
- Twitter : julienng_c
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Merci, ton talk sera présenté le 14 mars 2023 à la Plage Digitale, je t'invite à nous rejoindre [sur notre discord](https://discord.gg/44Yd9CME8r) pour pouvoir s'organiser.

J'ajouterai qu'on pourrait proposer un temps de questions/réponses voire de débat suite à ta présentation.

À propos des signals, y a un repo qui compare les perfs de chacune des solutions: https://github.com/modderme123/js-reactivity-benchmark

**Comment by Julienng** [comment]
Super merci !

Oui, c'est une bonne idée !

J'avais vu passer ça oui, modderme123 est la personne qui travaille sur la v2 de solidjs, sur le benchmark, x-reactivity représente la V2 d'ailleurs de souvenir.

Pour le benchmark, je me suis basé sur celui-ci filtré sur les plus gros (angular, vue, react, preact, solid) : 
https://krausest.github.io/js-framework-benchmark/2023/table_chrome_110.0.5481.77.html

**Comment by edimitchel** [comment]
Vidéo: _à venir_
