### ISSUE TITLE
Maël Sicard-Cras: Meetup 13/03/23 lightning talk Clean Architecture

### ISSUE THREAD

**Issue by MSC29** [StrasbourgJS/talks#14]
# <Titre du talk>

### Contenu

La Clean Architecture; une architecture software qui permet de rendre indépendante la couche métier des technologies utilisées. 
Par conséquent, il est par example possible de changer de base de données sans avoir à changer le code de la logique métier.
Voyons comment ça fonctionne en théorie & en pratique.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [ ] 30 minutes
- [x] Précisez : 15 minutes

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Maël Sicard-Ctas
- Twitter : n/a
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by KeziahMoselle** [comment]
Le talk a été transféré au Strasbourg Developer Meetup (https://twitter.com/StrasDevMeetup).
