### ISSUE TITLE
Orion - Nouveau framework UI Vue 3 (made in Alsace)

### ISSUE THREAD

**Issue by jbmaisner** [StrasbourgJS/talks#18]
# Orion - Vue 3 UI Framework

### Contenu

Depuis environ 2 ans nous avons développé en interne **Orion**, un nouveau framework UI basé sur Vue 3, Typescript et Vite.
Nous avons souhaité rendre ce projet open-source afin de rendre à la communauté une infime partie de ce qu'elle nous apporte quotidiennement.
Il s'agit de notre premier véritable projet open-source. Nous avons plein de choses à apprendre et avons hâte de le partager.

Ce framework développé entre Colmar et Strasbourg aspire à être simple d'utilisation, à la fois pour les utilisateurs, mais aussi pour les contributeurs.

**Voici le lien vers la documentation : [orion-ui.org](https://orion-ui.org/).**

Je propose 2 options pour le talk : 
- Présenter uniquement le framework et les bases de son utilisation.
- Présenter également l'architecture que nous avons élaborée et utilisée pour la création du framework (architecture éprouvée au sein de nos projets internes), dont un aperçu est disponible [dans la documentation](https://orion-ui.org/contributing/component.html) ainsi que dans [cette RFC](https://github.com/vuejs/rfcs/discussions/481).

### Durée :

- [ ] 5 minutes (Lightning talk)
- [x] 10 minutes
- [x] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : MAISNER Jean-Brice
- Twitter : [https://twitter.com/jbmaisner](https://twitter.com/jbmaisner)
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by KeziahMoselle** [comment]
Voici le lien de la VOD: https://www.youtube.com/watch?v=yJ1adVN-fSg

**Comment by jbmaisner** [comment]
Top ! Merci beaucoup @KeziahMoselle
