### ISSUE TITLE
Push API : Enfin une compatibilité avec iOS 

### ISSUE THREAD

**Issue by Gab-Metzger** [StrasbourgJS/talks#20]
# Push API : Enfin une compatibilité avec iOS

### Contenu

Depuis la sortie de Safari 16.4, Apple a enfin décidé d'autoriser la réception des notifications push sur une PWA (progressive web app). Ce qui rend aujourd'hui tous les navigateurs compatibles et offre de nombreuses possibilités d'interactions avec les utilisateurs.
À travers ce petit talk je ferai une présentation rapide de la Push API et montrerai un exemple d'application sur une PWA développée pour l'occasion.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [x] 10 minutes
- [ ] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [ ] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : METZGER Gabriel
- Twitter : https://twitter.com/Gab_Metzger
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by KeziahMoselle** [comment]
Voici le lien de la VOD: https://www.youtube.com/watch?v=eXCCOP2GIeQ
