### ISSUE TITLE
Developer Experience with Nuxt DevTools

### ISSUE THREAD

**Issue by antfu** [StrasbourgJS/talks#21]
# Developer Experience with Nuxt DevTools

### Contenu

Introduction to Nuxt DevTools and how it could improve our day-to-day developer experience and help to improve our Nuxt application.

(Sorry, I am not yet fluent in French, so I will give it in English).

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [x] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [ ] Intermédiaire
- [x] Avancé

## À propos de vous

- Nom et prénom : Anthony Fu
- Twitter : antfu7
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

More info about me in cased needed: https://antfu.me/giving-talks

**Comment by KeziahMoselle** [comment]
And here's the VOD link! 👉 https://youtu.be/brXZw4HQBGY
