### ISSUE TITLE
Creative coding en JavaScript

### ISSUE THREAD

**Issue by sylvainpolletvillard** [StrasbourgJS/talks#23]
# Creative Coding en JavaScript

Salut, je découvre votre groupe StrasbourgJS. JavaScript est mon sujet passion et j'adore rencontrer d'autres devs pour en parler, alors je saisis l'opportunité pour faire connaissance et je tente ma chance avec un sujet un peu niche mais à la fois fun et technique.

## À propos du talk

JavaScript n'est pas le langage le plus performant ni le plus sûr, mais c'est de loin celui avec lequel j'ai pu être le plus créatif et avoir le plus de fun. Pour ceux qui ne connaissent pas, le creative coding est une forme d'art logiciel où le code fait partie intégrante de l'oeuvre, voire constitue l'oeuvre en elle-même. La discipline la plus connue en creative coding est la demoscene, qui a beaucoup marché dans les années 80-90. JavaScript fait survivre cette culture de la demoscene avec des compétitions comme la JS1k ou la js13kgames. Je suis moi-même creative coder en JS et ce talk se veut être une introduction au creative coding en JS, en exposant et expliquant les exemples les plus emblématiques et en m'attardant sur un projet sur lequel j'ai beaucoup contribué et qui reste inachevé, le Wall of Six.

### Contenu

- Introduction au creative coding: c'est quoi ? pourquoi ?
- Le code golf et les commus JavaScript de code golf
- La demoscene et une analyse rapide des meilleures démos des dernières JS1K
- Les Quines en JS, présentation du quine World de Martin "aem1k" Kleppe
- Les Polyglot en JS, présentation des travaux de Mathieu "p01" Henri
- Le Character Subsetting, présentation de mon projet XChars et du Wall of Six
- Conclusion et Q&A

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [x] 30 minutes
- [x] Précisez : je peux toujours raccourcir au besoin mais vous savez ce que c'est, on a toujours trop de choses à dire :)

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

Le talk se veut le plus ludique possible mais des débutants risquent d'être perdus lors de certains passages d'analyse technique

## À propos de vous

- Nom et prénom : Sylvain Pollet-Villard
- Twitter : @SylvainPV
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

Note: si ce sujet n'est pas adapté, je peux également proposer un talk sur les sujets suivants:
- les super-pouvoirs des Proxies en JS
- réconcilier programmation objet et programmation fonctionnelle en JS

**Comment by edimitchel** [comment]
Hello Sylvain,

Merci pour cette proposition fort intéressante !

On t'invite à nous rejoindre sur notre discord pour s'accorder pour le prochain Meetup: https://discord.gg/Vvs9zpp2.

On retient ton talk pour le prochain talk qui aura lieu normalement le 5 octobre ;)
