### ISSUE TITLE
SSR avec ViteJS sans meta framework

### ISSUE THREAD

**Issue by Giildo** [StrasbourgJS/talks#24]
# SSR avec ViteJS sans meta framework

### Contenu

Souvent le premier reflexe pour faire du SSR est de passer par un meta-framework (nuxt, next...). Mais vous avez déjà un projet réalisé en Vue, React et vous ne souhaitez pas tout refaire avec ce genre d'outil tout en profitant de SSR ? Avec ViteJS et quelques modifications dans votre projet, c'est possible !

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [X] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [X] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Jonathan Marco
- Twitter : @GiildoJm
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Sujet très intéressant ! As-tu prévu d'utiliser des packages de [Unjs](https://unjs.io/) ?

**Comment by Giildo** [comment]
> Sujet très intéressant ! As-tu prévu d'utiliser des packages de [Unjs](https://unjs.io/) ?

Non, justement ce qui est intéressant c'est de montrer qu'avec Vite+Vue pur tu peux déjà faire du SSR. Par contre, je peux mettre des lib dans un "Aller plus loin" pour montrer ce qui existe ensuite.

**Comment by edimitchel** [comment]
![IMG20231206194241](https://github.com/StrasbourgJS/talks/assets/2922851/d581c4d4-44fe-4a1c-9fce-c0b26fd6e47d)
