### ISSUE TITLE
Découvrons _ensemble_ l'écosystème UnJS

### ISSUE THREAD

**Issue by Barbapapazes** [StrasbourgJS/talks#26]
# Découvrons _ensemble_ l'écosystème UnJS 

## À propos du talk

30 minutes de découverte de l'écosystème UnJS et de la manière dont il peut servir aux développeurs. 

### Contenu

Historique, chiffres, paquets et utilisations, on passera au peigne fin UnJS d'une manière interactive et selon les volontés du public ! 

### Durée : 30 minutes maximum

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [x] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [ ] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Soubiran Estéban
- Twitter : soubiran_
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
https://youtu.be/mPcJXqaBLFM
