### ISSUE TITLE
Présentation d'AdonisJS 6

### ISSUE THREAD

**Issue by RomainLanz** [StrasbourgJS/talks#27]
# Présentation d'AdonisJS 6

## À propos du talk

Découverte du framework Node.js AdonisJS 6.

### Contenu

On commencera par une présentation de moi même ainsi que de mon parcours. Nécessaire afin de comprendre mes avis. Par la suite une introduction au framework de mon coeur, AdonisJS 6, sera réalisée. Et si le temps nous le permet, une démonstration du framework, notament du module Transmit et possiblement Inertia.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [ ] 30 minutes
- [x] Précisez : Environ 1 heure (à voir après les répétitions)

### Niveau :

- [x] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Lanz Romain
- Twitter : https://twitter.com/romainlanz
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
https://youtu.be/DDlP1yY4OYI
