### ISSUE TITLE
`Cool ton tool` : Linear

### ISSUE THREAD

**Issue by ThePrincelle** [StrasbourgJS/talks#29]
# `Cool ton tool` : Linear

### Contenu

Découverte de Linear ([linear.app](https://linear.app)), outil de gestion de projet. L'idée est de faire une présentation générale, rapide du produit, de montrer les capacités de ce dernier. 

### Durée :

- [ ] 5 minutes (Lightning talk)
- [x] 10 minutes (pas encore sûr)
- [ ] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [ ] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Maxime Princelle
- Twitter : https://twitter.com/ThePrincelle
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Merci pour ce talk !
Vidéo en cours d'édition.
