### ISSUE TITLE
Ionic débarque sur VueJS

### ISSUE THREAD

**Issue by Giildo** [StrasbourgJS/talks#3]
# Ionic débarque sur VueJS

### Contenu

Ionic qui permet de faire des applications proches des application natives sur smartphone a créé une version pour VueJS. Il permet en quelque ligne de code de faire des applications qui seront agnostiques de l'outils sur lequel on lit le site et surtout qui permettront d'utiliser des éléments du smartphone comme la caméra par exemple.

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [x] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Jonathan Marco
- Twitter : @GiildoJm

**Comment by edimitchel** [comment]
Salut @Giildo,
ta proposition a été sélectionnée pour le prochain meet-up, merci de nous contacter via twitter ([twitter.com/Strasbourg_js](https://twitter.com/Strasbourg_js)).

**Comment by KeziahMoselle** [comment]
https://twitter.com/Ionicframework/status/1328776241399345152

**Comment by edimitchel** [comment]
Encore merci pour ta première intervention en tant que Speaker ! C'était réussi !
Peut-être à une prochaine !
