### ISSUE TITLE
Introduction à Alpine.js

### ISSUE THREAD

**Issue by klauss-blackbird** [StrasbourgJS/talks#30]
# Introduction à Alpine.js

### Contenu

Ce talk a pour but d'introduire le framework Alpine.js, en le présentant et en faisant une démo sommaire des fonctionnalités de base

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [x] 20 minutes
- [ ] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [ ] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Klauss Mortreux
- LinkedIn : https://www.linkedin.com/in/klauss-mortreux/
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Hello, nous confirmons la participation de ton talk pour le prochain meet-up, tu peux venir sur notre discord pour prendre contact avec l'ensemble de l'équipe: https://discord.gg/Dfbf3R7Y (attention, utilisation unique du lien d'invitation)

**Comment by edimitchel** [comment]
Merci pour ce talk !
Vidéo en cours d'édition.
