### ISSUE TITLE
Luna Park : Un framework no-code basé sur les frameworks JS

### ISSUE THREAD

**Issue by hugoattal** [StrasbourgJS/talks#31]
# Luna Park : Un framework no-code basé sur les frameworks JS

### Contenu

Depuis 3 ans, je développe Luna Park (https://luna-park.app), une plateforme no-code qui permet de développer des webapps comme avec un framework moderne, mais sans code. Et c'est super intéressant, à la fois d'un point de vue technique, mais aussi de comment représenter le code visuellement.

Je pense séparer le talk en deux parties :

- Comment imaginer des interfaces graphiques pour tout ce qui existe en web: que ce soit le HTML, le JS ou le CSS, il faut permettre de tout faire sans code. Et c'est valable les systèmes de réactivité, de routing, de backend, de stores, de bases de données...

- Comment développer tout ça, faire en sorte que l'interface fonctionne en temps réel et faire tourner le frontend et le backend dans le browser. Comment compiler une webapp créée en code "réel" pour l'héberger sur Vercel ou son propre serveur.

Si vous pensez que certains trucs sont plus intéressants que d'autres, n'hésitez pas à me le suggérer :) ! Il y a tellement de choses à dire...

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [x] 30 minutes
- [ ] Précisez :

### Niveau :

- [ ] Débutant
- [x] Intermédiaire
- [ ] Avancé

La première partie est assez accessible avec des bases de frameworks JS comme Vue ou React.
La deuxième partie est un peu plus avancée, on parlera surtout d'algorithmie et de CSS.

## À propos de vous

- Nom et prénom : Hugo Attal
- Twitter : https://x.com/HugoAttal
- Bluesky : https://bsky.app/profile/hugo.attal.fr
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui** (ça dépends du jour cela dit vu que je suis à Paris)

**Comment by edimitchel** [comment]
Rediffusion : https://www.youtube.com/watch?v=BmEBWiFhGsY
