### ISSUE TITLE
ReactNative, Jamstack, et bien plus encore

### ISSUE THREAD

**Issue by slorber** [StrasbourgJS/talks#6]
# ReactNative, Jamstack, et bien plus encore

### Contenu

Contrairement à d'autres technologies cross-platform, ReactNative est compatible avec la Jamstack.

Sébastien nous montrera comment il intègre ReactNative à son blog, et comment il utilise le même contenu MDX sur toutes les plateformes supportées par ReactNative, sans iframe ni WebView.

Nous utiliserons un large ensemble de technologies: Gatsby, MDX, React-Native (web, iOS, Android, MacOS...), Expo, React-Navigation, Netlify...

### Durée :

- [x] 30 minutes

### Niveau :

- [ ] Débutant
- [ ] Intermédiaire
- [X] Avancé

## À propos de vous

- Nom et prénom : Lorber Sébastien
- Twitter : https://twitter.com/sebastienlorber
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Merci Sébastien, nous confirmons ton sujet pour le prochain talk. 👌
Confirmes-ty vouloir bien le faire en live ?

**Comment by slorber** [comment]
hello

oui en live c'est possible vu que je n'ai pas d'enregistrement sans branding en français de cette présentation

**Comment by edimitchel** [comment]
Encore merci Sébastien pour ton intervention ! 
Nous tenons à te faire part d'un petit point d'amélioration : privilégie l'usage d'un micro adapté pour un live.
Nous avions pas vérifier à temps que le son était ok. Heureusement, nous avions réglé le problème d'écho à temps :)

Et peut-être à une prochaine !

**Comment by slorber** [comment]
Merci pour le retour

selon toi, qu'est-ce qu'un micro adapté pour le live?
je viens d'acheter un micro pour podcast blue yeti que je ne maitrise encore pas vraiment, et on m'a dit qu'il captait encore plus les bruits dans la piece comme les bruits de chaise qui bascule etc, du coup je ne l'ai pas utilisé

**Comment by edimitchel** [comment]
J'ai aussi voulu prendre un micro de ce genre, mais effectivement, c'est un micro trop efficace qui prendra en compte aussi l'imperfection de la salle où tu es (écho, bruits ambiants).
Je t'invite à regarder https://fr.ehomerecordingstudio.com/traitement-acoustique/.
Il a plusieurs solutions envisageable à moindre coût :)

**Comment by slorber** [comment]
Ca me semble un peu compliqué par rapport à mon besoin tout ça quand même 😅
