### ISSUE TITLE
Automatisation et DevOps dans le monde du JavaScript

### ISSUE THREAD

**Issue by Divlo** [StrasbourgJS/talks#7]
# Automatisation et DevOps dans le monde du JavaScript

### Contenu :

- Premier exemple d'automatisation : création d'un nouveau projet avec [create-fullstack-app](https://github.com/Divlo/create-fullstack-app)
- Introduction au DevOps visant à l'unification des outils pour le développement d'un projet afin de réduire le "time to market"
- Collaboration en équipe avec `git` et le concept de`Gitflow`
- Suite de la collaboration en équipe par la compréhension de son propre code en suivant les principes de code les plus connus (comme DRY ou Keep It Simple, Stupid).
- [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), [Semantinc Versioning](https://semver.org/), [keep a changelog](https://keepachangelog.com/en/1.0.0/) et le package [release-it](https://www.npmjs.com/package/release-it)
- Continous integration: Linting du code, les tests unitaires, mise à jour des dépendances automatiquement, etc. avec GitHub Actions
- Continuous deployment: GitHub Pages, Vercel, Netflify etc. pour déployer automatiquement son application
- Introduction à Docker (à quoi ça sert et comment s'en servir si le fichier `docker-compose.yml` existe déjà à la racine du projet)
- Exemple du site web de @StrasbourgJS

### Pourquoi ce talk ?

D'après moi, trop de débutants commencent à coder sans se soucier de la lisibilité et les performances du code, leur seul objectif c'est que ça fonctionne rien d'autre alors qu'un code qui fonctionne, ce n'est pas forcément un code prêt pour la production.
Le déploiement (avec un ftp comme [FileZilla](https://filezilla-project.org/) par exemple) et tester son code manuellement prend trop de temps et surtout est source d'erreurs.

L'intérêt de ce talk est donc d'introduire les bonnes pratiques (subjectivement) de code et d'éviter les erreurs dans ses futurs projets.

### Durée :

- [ ] 10 minutes
- [ ] 20 minutes
- [ ] 30 minutes
- [ ] 1 heure
- [x] Précisez : À décider (sûrement un talk de 1h car ce sont des concepts complexes et chacun d'eux mériterait un talk entier pour en parler, ici c'est seulement une introduction)

### Niveau :

- [ ] Débutant
- [x] Intermédiaire (au moins des connaissances en Git, npm et JS sont nécessaires)
- [ ] Avancé

## À propos de vous

- Nom et prénom : LUDWIG Théo
- Twitter : https://twitter.com/Divlo_FR
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**, avec plaisir mais pour le moment rien n'est préparé encore, il me faudra sûrement du temps avant de présenter quelque chose (diapo, contenu etc.)

**Comment by edimitchel** [comment]
@Divlo Comme convenu, ce talk sera sous la forme d'un workshop.
Peux-tu créer un nouveau ticket le lightning talk comme annonce du workshop ?

**Comment by Divlo** [comment]
@edimitchel Je préfère ne pas mélanger les choses pour le moment. C'est mieux qu'on discute ici du talk ou workshop, une fois qu'on aura les idées claires oui, on pourra faire une nouvelle issue mais là ce n'est pas la peine je pense.

**Comment by KeziahMoselle** [comment]
Hello @Divlo,
Est-ce que tu souhaites présenter un peu le sujet sous forme de talk pour le meet-up prochain ? 😄
