### ISSUE TITLE
Nuxt : SSR et SSG dans ta Vue

### ISSUE THREAD

**Issue by ElisePatrikainen** [StrasbourgJS/talks#9]
# Nuxt : SSR et SSG dans ta Vue

### Contenu

Les différents modes de rendus (SSR et SSG) sont une feature clé de Nuxt. Il est donc difficile d'appréhender la framework sans une bonne compréhension ces derniers. Dans ce talk, nous allons essayer de démystifier ces concept, afin d'en saisir concrètement le fonctionnement, et d'en déduire les inconvénients et (surtout ;p) les avantages. 

Plan
- Introduction à Nuxt
- le SSR
- le SSG

### Durée :

- [ ] 5 minutes (Lightning talk)
- [ ] 10 minutes
- [ ] 20 minutes
- [x] 30 minutes
- [ ] Précisez :

### Niveau :

- [x] Débutant
- [x] Intermédiaire
- [ ] Avancé

## À propos de vous

- Nom et prénom : Elise Patrikainen
- Twitter : @ElisePatrikain1
- Souhaitez-vous présenter ce sujet lors d'un prochain meet-up ? **Oui**

**Comment by edimitchel** [comment]
Bonjour Élise,
Comme convenu, peux-tu modifier le contenu de ta présentation ?

**Comment by ElisePatrikainen** [comment]
Bonjour Michel,
C'est noté, je le fais asap.

**Comment by ElisePatrikainen** [comment]
C'est fait.
